apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: amrut-crds.com.amrut.prabhu
spec:
  preserveUnknownFields: false
  group: com.amrut.prabhu
  names:
    kind: amrut-crd
    plural: amrut-crds
    listKind: amrut-crd-list
    singular: amrut-crd
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                name: 
                  type: string
              type: object
            status:
              properties:
                name:
                  type: string
              type: object
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: [] 