/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amrut.prabhu.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1MyCrdSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-02T11:18:30.292Z[Etc/UTC]")
public class V1MyCrdSpec {
  public static final String SERIALIZED_NAME_MY_OWN_PROPERTY = "my-own-property";
  @SerializedName(SERIALIZED_NAME_MY_OWN_PROPERTY)
  private String myOwnProperty;


  public V1MyCrdSpec myOwnProperty(String myOwnProperty) {
    
    this.myOwnProperty = myOwnProperty;
    return this;
  }

   /**
   * Get myOwnProperty
   * @return myOwnProperty
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMyOwnProperty() {
    return myOwnProperty;
  }


  public void setMyOwnProperty(String myOwnProperty) {
    this.myOwnProperty = myOwnProperty;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1MyCrdSpec v1MyCrdSpec = (V1MyCrdSpec) o;
    return Objects.equals(this.myOwnProperty, v1MyCrdSpec.myOwnProperty);
  }

  @Override
  public int hashCode() {
    return Objects.hash(myOwnProperty);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1MyCrdSpec {\n");
    sb.append("    myOwnProperty: ").append(toIndentedString(myOwnProperty)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

